Repository selsa-inube/isetting, pull requests merged in 2023-10, with the labels that each got.

#363 Update: Install new design-system version and restrict routes
  package-lock.json
  package.json
  src/App.tsx
  src/routes/login.tsx
  src/routes/privileges.tsx
  src/routes/respondInvitation.tsx
Labels: major, dependencies

#369 Uncomment `loading-app` route in `routes/login.tsx
  src/routes/login.tsx
Labels: minor

#365 uncomment `login` in `App tsx`
  src/App.tsx
  src/pages/login/errors/ErrorNotClient/index.tsx
  src/pages/login/index.tsx
  src/pages/login/interface.tsx
Labels: minor

#367 Uncomment "checking-credentials" route in `routes/login.tsx`
  src/routes/login.tsx
Labels: minor

#370 refactor usage of <Stack />, <Text /> and <Spinner /> in <LoadingAppUI/>
  src/pages/login/outlets/LoadingApp/interface.tsx
Labels: minor

#368 refactor usage of `<Stack />`, `<Text />` and `<Spinner />` in `<CheckingCredentialsUI />`
  src/pages/home/interface.tsx
  src/pages/login/outlets/CheckingCredentials/interface.tsx
Labels: minor

#373 Uncomment "privileges/*" in App.tsx
  src/App.tsx
Labels: minor

#371 Uncomment "clients" route in routes/login.tsx
  src/pages/login/outlets/Clients/interface.tsx
  src/routes/login.tsx
Labels: minor

#374 Integration: Merge Stable Code into Development
  package-lock.json
  package.json
  src/App.tsx
  src/components/PageTitle/index.tsx
  src/pages/home/interface.tsx
  src/pages/login/errors/ErrorNotClient/index.tsx
  src/pages/login/index.tsx
  src/pages/login/interface.tsx
  src/pages/login/outlets/CheckingCredentials/interface.tsx
  src/pages/login/outlets/Clients/interface.tsx
  src/pages/login/outlets/LoadingApp/interface.tsx
  src/routes/login.tsx
  src/routes/privileges.tsx
  src/routes/respondInvitation.tsx
  vite.config.ts
Labels: patch

#375 `<PageTitle />:` refactor to use `<Icon />`
  src/components/PageTitle/index.tsx
  src/components/PageTitle/styles.ts
Labels: minor

#379 Uncomment `/*` route in `routes/privileges.tsx`
  src/routes/privileges.tsx
Labels: minor

#377 `Enhancement:` Re-enable Root and "Options" Routes in Privileges
  src/components/cards/AppMenuCard/index.tsx
  src/components/layout/AppMenu/index.tsx
  src/components/layout/AppMenu/types.ts
  src/pages/home/config/apps.config.tsx
  src/pages/privileges/outlets/options/index.tsx
  src/pages/privileges/outlets/options/interface.tsx
  src/routes/privileges.tsx
Labels: minor

#380 `<ErrorPage />:` refactor the usage of `Stack`, `Text`, `Button` and `Grid`
  src/components/layout/ErrorPage/index.tsx
  src/components/layout/ErrorPage/styles.ts
Labels: minor

#378 `<AppMenuCard />:` refactor usage of `<Stack/>` and `<Text/>`
  src/components/cards/AppMenuCard/index.tsx
  src/components/cards/AppMenuCard/styles.ts
Labels: minor

#376 refactor usage of `<Stack />`, `<Text />` and `useMediaQuery` in `<PageTitle />`
  src/components/PageTitle/index.tsx
Labels: minor

#381 `<ClientsUI/>:` refactor to use new spacing tokens
  src/pages/login/outlets/Clients/styles.ts
Labels: minor

#382 Refactor usage of `<Breadcrumbs />` and `<Grid />`
  src/components/PageTitle/index.tsx
  src/components/cards/AppMenuCard/index.tsx
  src/components/layout/AppMenu/AppMenu.stories.tsx
  src/components/layout/AppMenu/index.tsx
  src/components/layout/AppMenu/styles.ts
  src/pages/privileges/outlets/options/interface.tsx
Labels: minor

#383 `Fix:` ensure the proper functionality of the login module and its associated dependencies
  src/pages/login/interface.tsx
  src/routes/login.tsx
Labels: bug

#384 `Fix`: ensure the proper icon-color's use along `<AppMenu/>`,`<AppMenuCard />`, `<PageTitle />`
  src/components/PageTitle/index.tsx
  src/components/cards/AppCard/index.tsx
  src/components/cards/AppCard/styles.ts
Labels: bug
