Repository selsa-inube/isetting, pull requests merged in 2023-07, with the labels that each got.

#291 jg/422/migrate-login-page-to-typeScript
  src/pages/login/errors/ErrorNotAvailable/index.tsx
  src/pages/login/errors/ErrorNotClient/index.tsx
  src/pages/login/index.tsx
  src/pages/login/interface.tsx
  src/pages/login/outlets/CheckingCredentials/CheckingCredentials.stories.tsx
  src/pages/login/outlets/CheckingCredentials/index.tsx
  src/pages/login/outlets/CheckingCredentials/interface.tsx
  src/pages/login/outlets/Clients/Clients.stories.tsx
  src/pages/login/outlets/Clients/index.tsx
  src/pages/login/outlets/Clients/interface.tsx
  src/pages/login/outlets/Clients/styles.ts
  src/pages/login/outlets/Clients/types.ts
  src/pages/login/outlets/LoadingApp/LoadingApp.stories.tsx
  src/pages/login/outlets/LoadingApp/index.tsx
  src/pages/login/outlets/LoadingApp/interface.tsx
  src/pages/login/styles.ts
Labels: minor

#303 sl/440/design-system-to-5.1.0
  package-lock.json
  package.json
Labels: dependencies

#301 fix(editUser): adjust labels of edit user and complete registration
  src/pages/privileges/outlets/users/complete-invitation/config/completeInvitation.config.jsx
  src/pages/privileges/outlets/users/complete-invitation/interface.jsx
  src/pages/privileges/outlets/users/edit-user/config/editUser.config.jsx
  src/pages/privileges/outlets/users/edit-user/interface.jsx
Labels: patch

#302 sl/230/respond-invitation
  src/App.tsx
  src/assets/images/Completed.png
  src/assets/images/Expired.png
  src/components/inputs/Fieldset/index.tsx
  src/components/inputs/Fieldset/styles.ts
  src/mocks/apps/privileges/invitations.mock.jsx
  src/mocks/respondInvitation/themeClients.mock.tsx
  src/pages/privileges/outlets/users/invite/index.jsx
  src/pages/respondInvitation/RespondInvitation.stories.tsx
  src/pages/respondInvitation/cases/ConfirmationRegisterComplete/ConfirmationRegisterComplete.stories.tsx
  src/pages/respondInvitation/cases/ConfirmationRegisterComplete/index.tsx
  src/pages/respondInvitation/cases/ErrorInvitationExpired/ErrorInvitationExpired.stories.tsx
  src/pages/respondInvitation/cases/ErrorInvitationExpired/index.tsx
  src/pages/respondInvitation/cases/ErrorNotAvailable/ErrorNotAvailable.stories.tsx
  src/pages/respondInvitation/cases/ErrorNotAvailable/index.tsx
  src/pages/respondInvitation/index.tsx
  src/pages/respondInvitation/interface.tsx
  src/pages/respondInvitation/styles.ts
  src/pages/respondInvitation/types.ts
  src/routes/respondInvitation.tsx
  src/validations/regularExpressions.ts
  src/validations/validationMessages.ts
  src/validations/validationRules.ts
Labels: major

#304 Ap/430/separate data from invitations users
  src/mocks/apps/privileges/invitations/aidBudgetsForm.mock.jsx
  src/mocks/apps/privileges/invitations/branchesForm.mock.jsx
  src/mocks/apps/privileges/invitations/eventsForm.mock.jsx
  src/mocks/apps/privileges/invitations/invitations.mock.jsx
  src/mocks/apps/privileges/invitations/payrollsForm.mock.jsx
  src/mocks/apps/privileges/invitations/projectsForm.mock.jsx
  src/mocks/apps/privileges/users/aidBudgetsForm.mock.jsx
  src/mocks/apps/privileges/users/branchesForm.mock.jsx
  src/mocks/apps/privileges/users/eventsForm.mock.jsx
  src/mocks/apps/privileges/users/payrollsForm.mock.jsx
  src/mocks/apps/privileges/users/projectsForm.mock.jsx
  src/mocks/apps/privileges/users/users.mock.jsx
  src/pages/privileges/outlets/users/complete-invitation/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/AidBudgetsForm.stories.jsx
  src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/BranchesForm.stories.jsx
  src/pages/privileges/outlets/users/edit-user/forms/EventsForm/EventsForm.stories.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/stories/GeneralInformationForm.stories.jsx
  src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/PayrollsForm.stories.jsx
  src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/ProjectsForm.stories.jsx
  src/pages/privileges/outlets/users/edit-user/index.jsx
  src/pages/privileges/outlets/users/tabs/invitations/index.jsx
  src/pages/privileges/outlets/users/tabs/users/index.jsx
  src/pages/respondInvitation/cases/ConfirmationRegisterComplete/index.tsx
  src/pages/respondInvitation/cases/ErrorInvitationExpired/ErrorInvitationExpired.stories.tsx
  src/pages/respondInvitation/cases/ErrorNotAvailable/ErrorNotAvailable.stories.tsx
  src/pages/respondInvitation/index.tsx
  src/routes/respondInvitation.tsx
Labels: major

#307 sl/450/end-point-privileges-branches
  src/mocks/linparData.json
Labels: minor

#308 feat(mocks): add linparData.json file
  src/mocks/linparData.json
Labels: minor

#310 sl/453/end-point-privileges-positions
  src/mocks/linparData.json
Labels: minor

#312 feat(events): create privileges-events endpoint
  src/mocks/linparData.json
Labels: minor

#316 feat(mocks): add projects endpoints
  src/mocks/linparData.json
Labels: minor

#306 fix(generalInformation): adjust general informations buttons and hasC…
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
Labels: patch

#317 jg/452/create-end-point-privileges-payrolls
  src/mocks/linparData.json
Labels: minor

#309 sl/396/control-actions-view
  src/components/feedback/InteractiveModal/index.tsx
  src/components/feedback/InteractiveModal/stories/InteractiveModal.stories.tsx
  src/components/feedback/InteractiveModal/styles.ts
  src/components/forms/templates/AssignmentForm/stories/AssignmentForm.stories.tsx
  src/pages/privileges/outlets/users/tabs/invitations/CompleteInvitationLink/index.jsx
  src/pages/privileges/outlets/users/tabs/invitations/DeleteInvitation/index.jsx
  src/pages/privileges/outlets/users/tabs/invitations/DeleteInvitation/interface.jsx
  src/pages/privileges/outlets/users/tabs/invitations/ResendInvitation/index.jsx
  src/pages/privileges/outlets/users/tabs/invitations/ResendInvitation/interface.jsx
  src/pages/privileges/outlets/users/tabs/invitations/index.jsx
  src/pages/privileges/outlets/users/tabs/users/ActivateUser/index.jsx
  src/pages/privileges/outlets/users/tabs/users/ActivateUser/interface.jsx
  src/pages/privileges/outlets/users/tabs/users/DeleteUser/index.jsx
  src/pages/privileges/outlets/users/tabs/users/DeleteUser/interface.jsx
  src/pages/privileges/outlets/users/tabs/users/EditUser/index.jsx
  src/pages/privileges/outlets/users/tabs/users/index.jsx
Labels: patch

#318 jg/383/enable-step-change-clicking-assisted
  src/components/feedback/Assisted/StepBar/styles.ts
  src/components/feedback/Assisted/StepIndicator/index.tsx
  src/components/feedback/Assisted/StepIndicator/styles.ts
  src/components/feedback/Assisted/index.tsx
  src/components/feedback/Assisted/interface.tsx
Labels: minor

#321 sl/473/design-system-to-5.2.0
  package-lock.json
  package.json
Labels: dependencies

#320 sl/464/remove-non-available-nav
  .gitignore
  src/components/layout/AppMenu/styles.ts
  src/pages/home/config/apps.config.tsx
  src/pages/privileges/outlets/options/config/privileges.config.jsx
Labels: minor

#322 feat(dependencies): update design-system v5.3.0
  package-lock.json
  package.json
Labels: dependencies

#323 sl/468/end-point-create-invitation
  src/mocks/linparData.json
Labels: minor

#325 sl/480/design-system-to-5.3.1
  package-lock.json
  package.json
Labels: dependencies

#324 sl/474/replace-interactive-modal
  src/components/cards/SubjectCard/index.tsx
  src/components/cards/SubjectCard/stories/SubjectCard.stories.tsx
  src/components/cards/SubjectCard/types.ts
  src/components/feedback/InteractiveModal/index.tsx
  src/components/feedback/InteractiveModal/stories/InteractiveModal.stories.tsx
  src/components/feedback/InteractiveModal/styles.ts
  src/components/feedback/InteractiveModal/types.ts
Labels: minor

#330 sl/481/options-to-typescript
  src/pages/privileges/outlets/options/config/privileges.config.tsx
  src/pages/privileges/outlets/options/index.tsx
  src/pages/privileges/outlets/options/interface.tsx
Labels: minor

#332 sl/488/users-config-to-typescript
  src/pages/privileges/outlets/users/config/activateUser.config.tsx
  src/pages/privileges/outlets/users/config/deleteUser.config.tsx
  src/pages/privileges/outlets/users/config/invitationsTable.config.tsx
  src/pages/privileges/outlets/users/config/menuInvitation.config.tsx
  src/pages/privileges/outlets/users/config/resendInvitationUser.config.tsx
  src/pages/privileges/outlets/users/config/types.ts
  src/pages/privileges/outlets/users/config/usersTable.config.tsx
  src/pages/privileges/outlets/users/config/usersTabs.config.tsx
Labels: minor

#333 sl/486/users-to-typescript
  src/pages/privileges/outlets/options/interface.tsx
  src/pages/privileges/outlets/users/Users.stories.tsx
  src/pages/privileges/outlets/users/config/activateUser.config.tsx
  src/pages/privileges/outlets/users/config/deleteUser.config.tsx
  src/pages/privileges/outlets/users/config/resendInvitationUser.config.tsx
  src/pages/privileges/outlets/users/index.tsx
  src/pages/privileges/outlets/users/interface.tsx
  src/pages/privileges/outlets/users/styles.ts
  src/pages/privileges/outlets/users/types.ts
Labels: minor

#331 jg/484/migrate-invite-page-to-TypeScript
  src/pages/privileges/outlets/users/invite/Invite.stories.tsx
  src/pages/privileges/outlets/users/invite/config/messageInvitationSent.config.tsx
  src/pages/privileges/outlets/users/invite/config/usersInvitations.config.tsx
  src/pages/privileges/outlets/users/invite/index.tsx
  src/pages/privileges/outlets/users/invite/interface.tsx
  src/pages/privileges/outlets/users/invite/styles.ts
  src/pages/privileges/outlets/users/invite/types.ts
  src/types/messages.types.ts
Labels: minor

#334 sl/487/privileges-to-typescript
  src/pages/privileges/index.tsx
  src/pages/privileges/interface.tsx
  src/pages/privileges/styles.js
Labels: minor

#336 sl/504/design-system-to-5.4.0
  package-lock.json
  package.json
Labels: dependencies

#337 sl/493/spinner-save-general-form
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
Labels: patch

#338 sl/492/assign-form-switch-buttons
  src/components/forms/templates/AssignmentForm/index.tsx
  src/components/forms/templates/AssignmentForm/interface.tsx
Labels: patch

#329 jg/482/migrate-complete-invitation-page-to-TypeScript
  src/pages/privileges/outlets/users/complete-invitation/CompleteInvitation.stories.tsx
  src/pages/privileges/outlets/users/complete-invitation/config/completeInvitation.config.tsx
  src/pages/privileges/outlets/users/complete-invitation/config/invitationNotFound.config.tsx
  src/pages/privileges/outlets/users/complete-invitation/index.tsx
  src/pages/privileges/outlets/users/complete-invitation/interface.tsx
  src/pages/privileges/outlets/users/complete-invitation/styles.ts
  src/pages/privileges/outlets/users/config/activateUser.config.tsx
  src/pages/privileges/outlets/users/config/deleteUser.config.tsx
  src/pages/privileges/outlets/users/config/resendInvitationUser.config.tsx
  src/pages/privileges/outlets/users/types/actions.types.ts
  src/pages/privileges/outlets/users/types/forms.types.ts
Labels: minor

#335 sl/491/header-from-design-system
  src/components/Header/index.tsx
  src/components/Header/interface.tsx
  src/components/Header/stories/Header.stories.tsx
  src/components/Header/stories/HeaderController.tsx
  src/components/Header/styles.ts
  src/components/layout/AppPage/index.tsx
  src/components/layout/AppPage/styles.ts
  src/pages/home/interface.tsx
Labels: minor

#339 sl/495/responsive-invitations-table
  src/pages/privileges/outlets/users/config/invitationsTable.config.tsx
Labels: patch

#348 sl/511/users-tabs-to-spanish
  src/pages/privileges/outlets/users/config/usersTabs.config.tsx
Labels: patch

#350 sl/514/invite-button-to-spanish
  src/pages/privileges/outlets/users/interface.tsx
Labels: patch

#349 sl/513/headers-users-invitations-spanish
  src/pages/privileges/outlets/users/config/invitationsTable.config.tsx
  src/pages/privileges/outlets/users/config/usersTable.config.tsx
  src/pages/privileges/outlets/users/tabs/invitations/index.jsx
  src/pages/privileges/outlets/users/tabs/users/index.jsx
Labels: patch

#355 sl/518/placeholder-login-clients-spanish
  src/pages/login/outlets/Clients/interface.tsx
Labels: patch

#358 sl/515/logout-link-to-spanish
  package-lock.json
  src/components/layout/AppPage/index.tsx
Labels: patch

#357 jg/533/border-radius-on-assisted-background
  src/components/feedback/Assisted/styles.ts
  src/pages/privileges/outlets/users/complete-invitation/interface.tsx
Labels: patch

#360 feat(users): navigate to specific tab in page
  src/pages/privileges/outlets/users/index.tsx
  src/pages/privileges/outlets/users/invite/index.tsx
  src/pages/privileges/outlets/users/invite/interface.tsx
Labels: minor

#352 jg/466/connect login pages using mocked endpoints
  .env
  .gitignore
  src/mocks/linparData.json
  src/pages/login/errors/ErrorNotClient/index.tsx
  src/pages/login/index.tsx
  src/pages/login/outlets/CheckingCredentials/index.tsx
  src/pages/login/outlets/Clients/index.tsx
  src/pages/login/outlets/Clients/interface.tsx
  src/pages/login/outlets/Clients/types.ts
  src/pages/login/outlets/LoadingApp/index.tsx
  src/pages/login/types.ts
  src/routes/login.tsx
Labels: major

#361 sl/471/verification-step-assisted
  src/components/data/Accordion/index.tsx
  src/components/data/Accordion/stories/Accordion.stories.tsx
  src/components/data/Accordion/styles.ts
  src/components/feedback/Assisted/VerificationStep/index.tsx
  src/components/feedback/Assisted/index.tsx
  src/components/feedback/Assisted/interface.tsx
  src/components/feedback/Assisted/styles.ts
  src/components/feedback/Assisted/types.ts
  src/components/feedback/DecisionModal/index.tsx
  src/components/forms/templates/AssignmentForm/index.tsx
  src/components/forms/templates/AssignmentForm/interface.tsx
  src/components/forms/templates/AssignmentForm/styles.ts
  src/pages/privileges/outlets/users/complete-invitation/config/completeInvitation.config.tsx
  src/pages/privileges/outlets/users/complete-invitation/index.tsx
  src/pages/privileges/outlets/users/complete-invitation/interface.tsx
  src/pages/privileges/outlets/users/edit-user/config/editUser.config.tsx
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/index.tsx
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/index.tsx
  src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/EventsForm/index.tsx
  src/pages/privileges/outlets/users/edit-user/forms/EventsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.tsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/styles.ts
  src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/index.tsx
  src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/index.tsx
  src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/interface.tsx
  src/pages/privileges/outlets/users/index.tsx
  src/pages/privileges/outlets/users/interface.tsx
  src/pages/privileges/outlets/users/types/users.types.ts
  src/pages/respondInvitation/interface.tsx
  src/types/messages.types.ts
Labels: major

#359 Ap/485/migrate tabs to type script
  src/components/feedback/DecisionModal/index.tsx
  src/components/feedback/SectionMessage/index.tsx
  src/components/feedback/SectionMessage/stories/SectionMessage.stories.tsx
  src/pages/privileges/outlets/users/complete-invitation/config/completeInvitation.config.tsx
  src/pages/privileges/outlets/users/config/activateUser.config.tsx
  src/pages/privileges/outlets/users/config/deleteUser.config.tsx
  src/pages/privileges/outlets/users/config/invitationsTable.config.tsx
  src/pages/privileges/outlets/users/config/resendInvitationUser.config.tsx
  src/pages/privileges/outlets/users/edit-user/config/editUser.config.tsx
  src/pages/privileges/outlets/users/edit-user/config/messages.config.tsx
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/EventsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/config/messages.config.tsx
  src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/interface.tsx
  src/pages/privileges/outlets/users/index.tsx
  src/pages/privileges/outlets/users/interface.tsx
  src/pages/privileges/outlets/users/invite/config/messageInvitationSent.config.tsx
  src/pages/privileges/outlets/users/tabs/invitations/CompleteInvitationLink/index.tsx
  src/pages/privileges/outlets/users/tabs/invitations/CompleteInvitationLink/styles.ts
  src/pages/privileges/outlets/users/tabs/invitations/DeleteInvitation/index.tsx
  src/pages/privileges/outlets/users/tabs/invitations/DeleteInvitation/interface.tsx
  src/pages/privileges/outlets/users/tabs/invitations/DeleteInvitation/styles.ts
  src/pages/privileges/outlets/users/tabs/invitations/ResendInvitation/index.tsx
  src/pages/privileges/outlets/users/tabs/invitations/ResendInvitation/interface.tsx
  src/pages/privileges/outlets/users/tabs/invitations/ResendInvitation/styles.ts
  src/pages/privileges/outlets/users/tabs/invitations/index.tsx
  src/pages/privileges/outlets/users/tabs/users/ActivateUser/index.tsx
  src/pages/privileges/outlets/users/tabs/users/ActivateUser/interface.tsx
  src/pages/privileges/outlets/users/tabs/users/ActivateUser/types.ts
  src/pages/privileges/outlets/users/tabs/users/DeleteUser/index.tsx
  src/pages/privileges/outlets/users/tabs/users/DeleteUser/interface.tsx
  src/pages/privileges/outlets/users/tabs/users/DeleteUser/styles.ts
  src/pages/privileges/outlets/users/tabs/users/DeleteUser/types.ts
  src/pages/privileges/outlets/users/tabs/users/EditUser/index.tsx
  src/pages/privileges/outlets/users/tabs/users/EditUser/styles.ts
  src/pages/privileges/outlets/users/tabs/users/index.tsx
  src/pages/privileges/outlets/users/types/users.types.ts
  src/types/colors.types.ts
  src/types/messages.types.ts
  tsconfig.json
Labels: major
