Repository selsa-inube/isetting, pull requests merged in 2023-12, with the labels that each got.

#449 `Update:` Upgrade design-system to Latest Version in linpar
  package-lock.json
  package.json
Labels: minor

#447 Fix: remove `themeClientsMock` in Favor of design-system Theme
  src/mocks/respondInvitation/themeClients.mock.tsx
Labels: minor

#414 Update `<Assisted />` of the design system in `<CompleteInvitation />`
  package-lock.json
  src/pages/privileges/outlets/users/complete-invitation/config/completeInvitation.config.tsx
  src/pages/privileges/outlets/users/complete-invitation/index.tsx
  src/pages/privileges/outlets/users/complete-invitation/interface.tsx
Labels: minor

#452 implement Inube components in `<UserUI />`
  src/pages/privileges/outlets/users/index.tsx
  src/pages/privileges/outlets/users/interface.tsx
  src/pages/privileges/outlets/users/styles.ts
Labels: minor

#453 `Adjustment:` Enhance `<SectionMessage/>` for Improved Container Fit
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/EventsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/interface.tsx
  src/pages/privileges/outlets/users/interface.tsx
  src/pages/privileges/outlets/users/invite/interface.tsx
  src/pages/privileges/outlets/users/tabs/invitations/index.tsx
  src/pages/privileges/outlets/users/tabs/users/index.tsx
Labels: minor

#451 Add container for `<Nav />` component `Inube`
  src/components/layout/AppPage/index.tsx
  src/components/layout/AppPage/styles.ts
Labels: minor

#480 Capitalize only the first word in page title
  src/pages/privileges/outlets/users/edit-user/config/editUser.config.tsx
Labels: minor

#477 Fix spacing between `<Breadcrumbs />` and `<PageTitle />` in `<UserUI />`
  src/pages/privileges/outlets/users/interface.tsx
Labels: minor

#479 Fix: `Breadcrumb` Converting to Spanish
  src/pages/home/config/apps.config.tsx
  src/pages/privileges/outlets/options/config/privileges.config.tsx
  src/pages/privileges/outlets/users/complete-invitation/config/completeInvitation.config.tsx
  src/pages/privileges/outlets/users/edit-user/config/editUser.config.tsx
  src/pages/privileges/outlets/users/invite/config/usersInvitations.config.tsx
Labels: enhancement, minor

#483 Fix: Update Background Color and Spacing in `<Assisted/>` Component
  src/pages/privileges/outlets/users/complete-invitation/interface.tsx
  src/pages/privileges/outlets/users/complete-invitation/styles.ts
Labels: minor

#485 Update: Upgrade `linpar` Version to Align with New Release
  package-lock.json
  package.json
Labels: minor

#486 Update component Inube `<Texfield />` props in `<InviteUI />`
  src/pages/privileges/outlets/users/invite/interface.tsx
Labels: minor

#488 Fix: Correct `Breadcrumb` Functionality on Invite User Page
  src/components/layout/AppMenu/AppMenu.stories.tsx
  src/pages/privileges/outlets/options/config/privileges.config.tsx
  src/pages/privileges/outlets/users/complete-invitation/config/completeInvitation.config.tsx
  src/pages/privileges/outlets/users/edit-user/config/editUser.config.tsx
  src/pages/privileges/outlets/users/invite/config/usersInvitations.config.tsx
  src/pages/privileges/outlets/users/invite/interface.tsx
Labels: minor

#491 `Fix:` Ensure `<SectionMessage/>` Appears on Top of Content
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/styles.ts
  src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/styles.ts
  src/pages/privileges/outlets/users/edit-user/forms/EventsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/EventsForm/styles.ts
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/styles.ts
  src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/styles.ts
  src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/styles.ts
  src/pages/privileges/outlets/users/interface.tsx
  src/pages/privileges/outlets/users/invite/interface.tsx
  src/pages/privileges/outlets/users/invite/styles.ts
  src/pages/privileges/outlets/users/styles.ts
  src/pages/privileges/outlets/users/tabs/invitations/index.tsx
  src/pages/privileges/outlets/users/tabs/invitations/styles.ts
  src/pages/privileges/outlets/users/tabs/users/index.tsx
  src/pages/privileges/outlets/users/tabs/users/styles.ts
Labels: minor

#484 adjust the responsive on the `<RenderFormFields />` screen
  src/components/cards/SubjectCard/index.tsx
  src/components/cards/SubjectCard/styles.ts
  src/components/layout/AppPage/index.tsx
  src/components/layout/AppPage/styles.ts
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/styles.ts
Labels: minor

#492 `<UsersUI />`: the users and invitations tab shouldn't use a select tab in mobile
  src/pages/privileges/outlets/users/interface.tsx
Labels: minor

#490 `Fix: `Adjust Padding in `<UsersUI />` for Outlet Rendering in Privileges Process
  src/components/layout/AppPage/styles.ts
  src/pages/privileges/outlets/users/interface.tsx
Labels: minor

#489 `Fix:` Correct Responsive Width Issue in Main Section of `<AppPage/>`
  src/components/navigation/Menu/styles.ts
Labels: minor

#495 Change: Transition from JavaScript to TypeScript in app
  .storybook/main.ts
  .storybook/preview.tsx
  src/mocks/apps/privileges/invitations/aidBudgetsForm.mock.tsx
  src/mocks/apps/privileges/invitations/branchesForm.mock.tsx
  src/mocks/apps/privileges/invitations/eventsForm.mock.tsx
  src/mocks/apps/privileges/invitations/invitations.mock.tsx
  src/mocks/apps/privileges/invitations/payrollsForm.mock.tsx
  src/mocks/apps/privileges/invitations/projectsForm.mock.tsx
  src/mocks/apps/privileges/users/aidBudgetsForm.mock.tsx
  src/mocks/apps/privileges/users/branchesForm.mock.tsx
  src/mocks/apps/privileges/users/eventsForm.mock.tsx
  src/mocks/apps/privileges/users/payrollsForm.mock.tsx
  src/mocks/apps/privileges/users/projectsForm.mock.tsx
  src/mocks/apps/privileges/users/users.mock.tsx
  src/mocks/login/clients.mock.tsx
Labels: minor

#498 fix `<AppMenuCard />` update grid template column width
  src/components/layout/AppMenu/index.tsx
Labels: minor

#496 Feat: Implement auth0 for login
  .env
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
Labels: enhancement

#499 Update linpar's `package.json` for New Version of design-system
  package-lock.json
  package.json
Labels: minor

#501 Fix: Prevent Design Breakage when Opening Select Field in User Edition
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/styles.ts
  src/pages/privileges/outlets/users/edit-user/interface.tsx
  src/pages/privileges/outlets/users/edit-user/styles.ts
Labels: minor

#504 `fix:` `<EditUserUI/>` Adjust Spacing for "Invite User" Button
  src/components/navigation/Menu/styles.ts
  src/pages/privileges/outlets/users/edit-user/interface.tsx
  src/pages/privileges/outlets/users/interface.tsx
Labels: minor

#505 `Fix:` Adjust Right and Left Padding in `<UsersUI>` Component
  src/components/layout/AppPage/styles.ts
  src/pages/privileges/outlets/users/interface.tsx
Labels: minor

#507 `Feat(invite):` refactor `Invite User` Form to Include Query by Name and ID
  src/components/cards/SearchUserCard/SubjectCard.stories.tsx
  src/components/cards/SearchUserCard/index.tsx
  src/components/cards/SearchUserCard/styles.ts
  src/components/cards/SearchUserCard/types.ts
  src/components/cards/SubjectCard/SubjectCard.stories.tsx
  src/components/cards/SubjectCard/index.tsx
  src/components/cards/SubjectSearchCard/SubjectSearchCard.stories.tsx
  src/components/cards/SubjectSearchCard/index.tsx
  src/components/cards/SubjectSearchCard/styles.ts
  src/components/feedback/InteractiveModal/index.tsx
  src/components/feedback/InteractiveModal/styles.ts
  src/components/feedback/InteractiveModal/types.ts
  src/mocks/apps/privileges/users/usersSearchField.mock.tsx
  src/pages/privileges/outlets/users/invite/index.tsx
  src/pages/privileges/outlets/users/invite/interface.tsx
  src/pages/privileges/outlets/users/invite/types.ts
Labels: minor
