Repository selsa-inube/isetting, pull requests merged in 2023-06, with the labels that each got.

#189 sl/256/menu mobile invite user
  src/components/navigation/Menu/index.jsx
  src/components/navigation/Menu/stories/Menu.stories.jsx
  src/components/navigation/Menu/styles.js
  src/components/navigation/MenuLink/index.jsx
  src/components/navigation/MenuLink/stories/MenuLink.stories.jsx
  src/components/navigation/MenuLink/styles.js
  src/components/navigation/MenuOption/index.jsx
  src/components/navigation/MenuOption/stories/MenuOption.stories.jsx
  src/components/navigation/MenuOption/styles.js
  src/pages/privileges/outlets/users/config/menuInvitation.config.jsx
  src/pages/privileges/outlets/users/index.jsx
  src/pages/privileges/outlets/users/interface.jsx
  src/pages/privileges/outlets/users/styles.js
Labels: minor

#201 sl/327/update-design-system-4.0.0
  package-lock.json
  package.json
Labels: dependencies

#200 feat(pageTitle): adjust pageTitle to support backwards navigation
  src/components/PageTitle/PageTitle.stories.jsx
  src/components/PageTitle/index.jsx
  src/components/PageTitle/styles.js
  src/components/layout/AppMenu/AppMenu.stories.jsx
  src/components/layout/AppMenu/index.jsx
  src/pages/privileges/outlets/options/config/privileges.config.jsx
  src/pages/privileges/outlets/options/index.jsx
  src/pages/privileges/outlets/options/interface.jsx
  src/pages/privileges/outlets/users/complete-invitation/config/completeInvitation.config.jsx
  src/pages/privileges/outlets/users/complete-invitation/interface.jsx
  src/pages/privileges/outlets/users/edit-user/config/editUser.config.jsx
  src/pages/privileges/outlets/users/edit-user/interface.jsx
  src/pages/privileges/outlets/users/interface.jsx
  src/pages/privileges/outlets/users/invite/config/usersInvitations.config.jsx
  src/pages/privileges/outlets/users/invite/interface.jsx
Labels: patch

#204 jg/321/create-empty-state-screen-user-not-found
  src/assets/images/ItemNotFound.png
  src/components/layout/ItemNotFound/ItemNotFound.stories.jsx
  src/components/layout/ItemNotFound/index.jsx
  src/components/layout/ItemNotFound/styles.js
  src/pages/privileges/outlets/users/edit-user/EditUser.stories.jsx
  src/pages/privileges/outlets/users/edit-user/config/itemNotFound.config.jsx
  src/pages/privileges/outlets/users/edit-user/index.jsx
  src/pages/privileges/outlets/users/edit-user/interface.jsx
Labels: minor

#209 feat(dependencies): install typescript
  package-lock.json
  package.json
Labels: dependencies

#197 feat(invite): use Formik to control the invite user form
  src/pages/privileges/outlets/users/invite/config/usersInvitations.config.jsx
  src/pages/privileges/outlets/users/invite/index.jsx
  src/pages/privileges/outlets/users/invite/interface.jsx
Labels: minor

#183 Cr/232/general information form
  src/mocks/apps/privileges/users.mock.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/config/messageGeneralInfoConfig.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/stories/GeneralInformationForm.stories.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/styles.js
Labels: minor

#212 feat: configure migration to typeScript
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: major

#214 feat: update design system to version 4.1.1
  package-lock.json
  package.json
Labels: dependencies

#220 sl/295/projects-in-complete-invitation
  src/components/feedback/Assisted/index.jsx
  src/pages/privileges/outlets/users/complete-invitation/config/completeInvitation.config.jsx
  src/pages/privileges/outlets/users/complete-invitation/index.jsx
  src/pages/privileges/outlets/users/complete-invitation/interface.jsx
Labels: major

#215 feat(radioClient): migrate radioClient to typescript
  src/components/cards/RadioClient/RadioClient.stories.tsx
  src/components/cards/RadioClient/index.tsx
  src/components/cards/RadioClient/styles.ts
Labels: minor

#221 sl/296/events-in-complete-invitation
  src/pages/privileges/outlets/users/complete-invitation/interface.jsx
Labels: minor

#222 feat(completeInvitation): add branches form
  src/pages/privileges/outlets/users/complete-invitation/interface.jsx
Labels: minor

#225 jg/335/migrate-AppMenuCard-to-TypeScript
  src/components/cards/AppMenuCard/AppMenuCard.stories.tsx
  src/components/cards/AppMenuCard/index.tsx
  src/components/cards/AppMenuCard/styles.ts
Labels: minor

#223 feat(completeInvitation): add aid budget units form
  src/pages/privileges/outlets/users/complete-invitation/index.jsx
  src/pages/privileges/outlets/users/complete-invitation/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/interface.jsx
Labels: minor

#227 sl/288/projects-in-edit-user
  src/pages/privileges/outlets/users/edit-user/index.jsx
  src/pages/privileges/outlets/users/edit-user/interface.jsx
  src/pages/privileges/outlets/users/edit-user/tabs/generalInformation/index.jsx
Labels: minor

#229 feat(editUser): insert aid budget units form in editUser component
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/AidBudgetsForm.stories.jsx
  src/pages/privileges/outlets/users/edit-user/interface.jsx
Labels: minor

#231 sl/291/payroll-in-edit-user
  src/pages/privileges/outlets/users/edit-user/config/editUserTabs.config.jsx
  src/pages/privileges/outlets/users/edit-user/interface.jsx
Labels: minor

#226 feat(editUser): insert branches form inside editUser component
  src/pages/privileges/outlets/users/edit-user/interface.jsx
Labels: minor

#234 sl/368/menu-option-to-typescript
  src/components/navigation/MenuOption/index.tsx
  src/components/navigation/MenuOption/stories/MenuOption.stories.tsx
  src/components/navigation/MenuOption/styles.ts
Labels: minor

#233 feat(pageTitle): migrate pagetitle to typeScript
  src/components/PageTitle/PageTitle.stories.tsx
  src/components/PageTitle/index.tsx
  src/components/PageTitle/styles.ts
Labels: minor

#237 sl/374/design-system-to-4.2.0
  package-lock.json
  package.json
Labels: dependencies

#236 feat(menuLink): migrate menuLink component to typeScript
  src/components/navigation/MenuLink/index.tsx
  src/components/navigation/MenuLink/stories/MenuLink.stories.tsx
  src/components/navigation/MenuLink/styles.ts
Labels: minor

#217 Sl/316/button responsive table
  src/components/cards/SubjectCard/index.jsx
  src/components/data/Table/DisplayEntry/index.tsx
  src/components/data/Table/index.jsx
  src/components/data/Table/interface.jsx
  src/components/data/Table/types.ts
  src/components/feedback/InfoModal/index.jsx
  src/components/feedback/InfoModal/stories/InfoModal.stories.jsx
  src/components/feedback/InteractiveModal/index.tsx
  src/components/feedback/InteractiveModal/stories/InteractiveModal.stories.tsx
  src/components/feedback/InteractiveModal/styles.ts
  src/components/feedback/InteractiveModal/types.ts
  src/pages/privileges/outlets/users/tabs/invitations/index.jsx
  src/pages/privileges/outlets/users/tabs/users/index.jsx
Labels: major

#240 Sl/337/subject card to typescript
  src/components/cards/SubjectCard/index.tsx
  src/components/cards/SubjectCard/stories/SubjectCard.stories.jsx
  src/components/cards/SubjectCard/stories/SubjectCard.stories.tsx
  src/components/cards/SubjectCard/styles.ts
  src/components/data/Table/DisplayEntry/index.tsx
  src/components/data/Table/interface.jsx
  src/components/feedback/InteractiveModal/index.tsx
  src/components/feedback/InteractiveModal/stories/InteractiveModal.stories.tsx
  src/components/feedback/InteractiveModal/types.ts
Labels: major

#242 sl/362/app-menu-to-typescript
  src/components/PageTitle/index.tsx
  src/components/cards/AppCard/index.tsx
  src/components/cards/AppMenuCard/index.tsx
  src/components/layout/AppMenu/AppMenu.stories.tsx
  src/components/layout/AppMenu/index.tsx
  src/components/layout/AppMenu/styles.ts
  src/components/layout/AppMenu/types.ts
Labels: minor

#232 Cr/293/insert general information in invitation
  src/mocks/apps/privileges/invitations.mock.jsx
  src/mocks/apps/privileges/users.mock.jsx
  src/pages/privileges/outlets/users/complete-invitation/index.jsx
  src/pages/privileges/outlets/users/complete-invitation/interface.jsx
  src/pages/privileges/outlets/users/config/invitationsTable.config.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/stories/GeneralInformationForm.stories.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/styles.js
Labels: patch

#241 Ap/350/replace text from design system
  src/components/PageTitle/index.tsx
  src/components/cards/AppCard/index.tsx
  src/components/cards/AppMenuCard/index.tsx
  src/components/cards/RadioClient/index.tsx
  src/components/data/Table/Pagination/index.jsx
  src/components/data/Table/interface.jsx
  src/components/data/Text/index.jsx
  src/components/data/Text/styles.js
  src/components/inputs/Fieldset/index.jsx
  src/components/layout/ErrorPage/index.tsx
  src/components/layout/ItemNotFound/index.jsx
  src/components/navigation/Nav/index.jsx
  src/components/navigation/NavLink/index.jsx
  src/pages/login/interface.jsx
  src/pages/login/outlets/CheckingCredentials/interface.jsx
  src/pages/login/outlets/Clients/interface.jsx
  src/pages/login/outlets/LoadingApp/interface.jsx
Labels: minor

#246 jg/365/migrate-ItemNotFound-to-TypeScript
  src/components/layout/ItemNotFound/ItemNotFound.stories.tsx
  src/components/layout/ItemNotFound/index.tsx
  src/components/layout/ItemNotFound/styles.ts
Labels: minor

#244 sl/356/decision-modal-to-typescript
  src/components/data/Table/types.ts
  src/components/feedback/DecisionModal/index.tsx
  src/components/feedback/DecisionModal/stories/DecisionModal.stories.tsx
  src/components/feedback/DecisionModal/styles.ts
  src/components/feedback/InteractiveModal/index.tsx
  src/components/feedback/InteractiveModal/stories/InteractiveModal.stories.tsx
  src/components/feedback/InteractiveModal/types.ts
Labels: minor

#243 feat(fieldset): migrate fieldset component to typeScript
  src/components/inputs/Fieldset/index.tsx
  src/components/inputs/Fieldset/stories/Fieldset.stories.tsx
  src/components/inputs/Fieldset/styles.ts
Labels: minor

#248 jg/286/insert-general-information-form-edit-user
  src/pages/privileges/outlets/users/edit-user/index.jsx
  src/pages/privileges/outlets/users/edit-user/interface.jsx
Labels: minor

#239 feat(menu): migrate menu component to typeScript
  package-lock.json
  package.json
  src/components/navigation/Menu/index.tsx
  src/components/navigation/Menu/stories/Menu.stories.tsx
  src/components/navigation/Menu/styles.ts
  src/components/navigation/Menu/types.ts
Labels: minor

#261 jg/384/change-export-type-named-UsersTab-InvitationsTab
  src/pages/privileges/outlets/users/interface.jsx
  src/pages/privileges/outlets/users/tabs/invitations/index.jsx
  src/pages/privileges/outlets/users/tabs/users/index.jsx
Labels: patch

#262 sl/385/fix-fieldset-height
  src/components/forms/templates/AssignmentForm/styles.js
Labels: patch

#263 jg/387/fix-menu-button-assignment-in-forms
  src/components/forms/templates/AssignmentForm/index.jsx
Labels: patch

#265 sl/390/fix-empty-position-field
  src/mocks/apps/privileges/users.mock.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/styles.js
Labels: patch

#264 sl/388/forms-with-section-message
  src/pages/privileges/outlets/users/complete-invitation/interface.jsx
  src/pages/privileges/outlets/users/edit-user/config/messages.config.jsx
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/EventsForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/EventsForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/config/messages.config.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/interface.jsx
  src/pages/privileges/outlets/users/tabs/invitations/index.jsx
  src/pages/privileges/outlets/users/tabs/users/index.jsx
Labels: patch

#266 sl/392/fix-warning-regex
  src/pages/privileges/outlets/users/invite/index.jsx
Labels: patch

#269 sl/394/correct-not-found-text
  src/pages/privileges/outlets/users/complete-invitation/config/invitationNotFound.config.jsx
  src/pages/privileges/outlets/users/edit-user/config/itemNotFound.config.jsx
Labels: patch

#267 Cr/386/assign unassign are breaking
  src/components/forms/templates/AssignmentForm/interface.jsx
  src/components/forms/templates/AssignmentForm/styles.js
Labels: patch

#272 sl/359/form-buttons-to-typescript
  src/components/forms/submit/FormButtons/index.tsx
  src/components/forms/submit/FormButtons/stories/FormButtons.stories.tsx
  src/components/forms/submit/FormButtons/stories/stories.styles.ts
  src/components/forms/submit/FormButtons/styles.ts
Labels: minor

#268 Cr/358/migrate section message to type script
  src/components/feedback/SectionMessage/index.tsx
  src/components/feedback/SectionMessage/interface.tsx
  src/components/feedback/SectionMessage/stories/SectionMessage.stories.tsx
  src/components/feedback/SectionMessage/styles.ts
Labels: minor

#273 Ap/391/max width assisted
  src/components/feedback/Assisted/interface.jsx
  src/components/feedback/Assisted/stories/Assisted.stories.jsx
  src/components/feedback/Assisted/styles.js
Labels: patch

#275 feat(assignmentform): migrate assignmentform to typescript
  src/components/forms/templates/AssignmentForm/index.tsx
  src/components/forms/templates/AssignmentForm/interface.jsx
  src/components/forms/templates/AssignmentForm/interface.tsx
  src/components/forms/templates/AssignmentForm/stories/AssignmentForm.stories.tsx
  src/components/forms/templates/AssignmentForm/styles.ts
  src/components/forms/templates/AssignmentForm/types.ts
  src/components/navigation/Menu/types.ts
  src/components/navigation/MenuLink/index.tsx
  src/components/navigation/MenuOption/index.tsx
Labels: minor

#238 jg/354/replace-nav-from-design-system
  src/components/Header/interface.jsx
  src/components/Header/styles.js
  src/components/layout/AppPage/index.tsx
  src/components/layout/AppPage/styles.ts
  src/components/navigation/Nav/index.jsx
  src/components/navigation/Nav/stories/Nav.stories.jsx
  src/components/navigation/Nav/stories/stories.styles.jsx
  src/components/navigation/Nav/styles.js
  src/components/navigation/NavLink/index.jsx
  src/components/navigation/NavLink/stories/NavLink.stories.jsx
  src/components/navigation/NavLink/styles.js
  src/pages/home/config/apps.config.jsx
Labels: minor

#279 sl/373/progressbar-for-countdowbar
  src/components/feedback/ProgressBar/index.jsx
  src/components/feedback/ProgressBar/stories/ProgressBar.stories.jsx
  src/components/feedback/ProgressBar/styles.js
  src/components/feedback/SectionMessage/interface.tsx
Labels: minor

#278 Ap/236/modal confirmation changing tabs
  src/components/feedback/DecisionModal/index.tsx
  src/pages/privileges/outlets/users/edit-user/config/editUser.config.jsx
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/EventsForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/EventsForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/interface.jsx
  src/pages/privileges/outlets/users/edit-user/index.jsx
  src/pages/privileges/outlets/users/edit-user/interface.jsx
Labels: major

#285 sl/415/change-icon-subject-card
  src/components/cards/SubjectCard/index.tsx
  src/components/cards/SubjectCard/stories/SubjectCard.stories.tsx
  src/components/cards/SubjectCard/styles.ts
  src/pages/privileges/outlets/users/complete-invitation/interface.jsx
  src/pages/privileges/outlets/users/edit-user/interface.jsx
Labels: patch

#286 sl/416/priority-users-table
  src/pages/privileges/outlets/users/config/invitationsTable.config.jsx
  src/pages/privileges/outlets/users/config/usersTable.config.jsx
Labels: patch

#287 sl/417/fix-haschanges-prop
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/EventsForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/index.jsx
  src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/index.jsx
Labels: patch

#281 feat(validations): creation of validations folder
  src/pages/privileges/outlets/users/edit-user/forms/GeneralInfoForm/index.jsx
  src/pages/privileges/outlets/users/invite/index.jsx
  src/validations/regularExpressions.ts
  src/validations/validationMessages.ts
  src/validations/validationRules.ts
  tsconfig.json
  vite.config.ts
Labels: major

#288 sl/352/table-from-design-system
  src/components/data/Table/DisplayEntry/index.tsx
  src/components/data/Table/Pagination/index.jsx
  src/components/data/Table/Pagination/styles.js
  src/components/data/Table/index.jsx
  src/components/data/Table/interface.jsx
  src/components/data/Table/stories/Delete/index.jsx
  src/components/data/Table/stories/Delete/styles.js
  src/components/data/Table/stories/Edit/index.jsx
  src/components/data/Table/stories/Edit/styles.js
  src/components/data/Table/stories/Switch/index.jsx
  src/components/data/Table/stories/Switch/styles.js
  src/components/data/Table/stories/Table.stories.jsx
  src/components/data/Table/styles.js
  src/components/data/Table/types.ts
  src/components/feedback/InteractiveModal/index.tsx
  src/components/feedback/InteractiveModal/types.ts
  src/components/layout/AppPage/styles.ts
  src/mocks/apps/privileges/invitations.mock.jsx
  src/mocks/apps/privileges/users.mock.jsx
  src/pages/privileges/outlets/users/complete-invitation/index.jsx
  src/pages/privileges/outlets/users/edit-user/index.jsx
  src/pages/privileges/outlets/users/tabs/invitations/index.jsx
  src/pages/privileges/outlets/users/tabs/users/index.jsx
Labels: major

#290 feat(dependencies): update design system to 5.0.0
  package-lock.json
  package.json
Labels: dependencies

#289 sl/420/app-context-to-typescript
  src/context/index.jsx
  src/context/index.tsx
Labels: minor

#293 feat(styles): migrate styles to typescript
  src/styles/colors.ts
  src/styles/global.ts
  src/styles/typography.ts
Labels: minor

#294 feat(home): migrate Home component to typeScript
  src/components/PageTitle/index.tsx
  src/pages/home/Home.stories.tsx
  src/pages/home/config/apps.config.tsx
  src/pages/home/index.tsx
  src/pages/home/interface.tsx
  src/pages/home/styles.ts
  src/pages/home/types.ts
Labels: minor

#295 sl/419/header-to-typescript
  src/components/Header/index.tsx
  src/components/Header/interface.tsx
  src/components/Header/stories/Header.stories.tsx
  src/components/Header/stories/HeaderController.jsx
  src/components/Header/stories/HeaderController.tsx
  src/components/Header/styles.ts
  src/context/index.tsx
  src/context/types.ts
Labels: minor

#292 jg/423/migrate-login-routes-to-TypeScript
  src/components/layout/ErrorPage/index.tsx
  src/routes/login.tsx
Labels: minor

#296 sl/424/privileges-routes-to-typescript
  src/routes/privileges.tsx
Labels: minor
