Repository selsa-inube/isetting, pull requests merged in 2024-01, with the labels that each got.

#510 `Feat:` Implement Mock Screen for Text Color Token Editing and Review
  src/components/cards/TokenColorCard/TokenColorCard.stories.tsx
  src/components/cards/TokenColorCard/index.tsx
  src/components/cards/TokenColorCard/styles.ts
  src/pages/people/outlets/options/config/people.config.tsx
  src/pages/people/outlets/palette/config/palette.config.tsx
  src/pages/people/outlets/palette/index.tsx
  src/pages/people/outlets/palette/interface.tsx
Labels: minor

#512 Feat: Enhanced Mock Screen for Text Color Token Editing and Preview
  package-lock.json
  package.json
  src/components/cards/FieldsetColorCard/FieldsetColorCard.stories.tsx
  src/components/cards/FieldsetColorCard/index.tsx
  src/components/cards/FieldsetColorCard/styles.ts
  src/components/cards/TokenColorCard/TokenColorCard.stories.tsx
  src/components/cards/TokenColorCard/index.tsx
  src/components/cards/TokenColorCard/styles.ts
  src/pages/people/outlets/palette/index.tsx
  src/pages/people/outlets/palette/interface.tsx
  src/pages/people/outlets/palette/styles.ts
  src/pages/people/outlets/texts/config/colorTabs.config.tsx
  src/pages/people/outlets/texts/config/text.config.tsx
  src/pages/people/outlets/texts/form/DarkForm/index.tsx
  src/pages/people/outlets/texts/form/DarkForm/interface.tsx
  src/pages/people/outlets/texts/form/DarkForm/styles.ts
  src/pages/people/outlets/texts/form/ErrorForm/index.tsx
  src/pages/people/outlets/texts/form/ErrorForm/interface.tsx
  src/pages/people/outlets/texts/form/ErrorForm/styles.ts
  src/pages/people/outlets/texts/form/GrayForm/index.tsx
  src/pages/people/outlets/texts/form/GrayForm/interface.tsx
  src/pages/people/outlets/texts/form/GrayForm/styles.ts
  src/pages/people/outlets/texts/form/HelpForm/index.tsx
  src/pages/people/outlets/texts/form/HelpForm/interface.tsx
  src/pages/people/outlets/texts/form/HelpForm/styles.ts
  src/pages/people/outlets/texts/form/InformationForm/index.tsx
  src/pages/people/outlets/texts/form/InformationForm/interface.tsx
  src/pages/people/outlets/texts/form/InformationForm/styles.ts
  src/pages/people/outlets/texts/form/LightForm/index.tsx
  src/pages/people/outlets/texts/form/LightForm/interface.tsx
  src/pages/people/outlets/texts/form/LightForm/styles.ts
  src/pages/people/outlets/texts/form/PrimaryForm/index.tsx
  src/pages/people/outlets/texts/form/PrimaryForm/interface.tsx
  src/pages/people/outlets/texts/form/PrimaryForm/styles.ts
  src/pages/people/outlets/texts/form/SuccessForm/index.tsx
  src/pages/people/outlets/texts/form/SuccessForm/interface.tsx
  src/pages/people/outlets/texts/form/SuccessForm/styles.ts
  src/pages/people/outlets/texts/form/WarningForm/index.tsx
  src/pages/people/outlets/texts/form/WarningForm/interface.tsx
  src/pages/people/outlets/texts/form/WarningForm/styles.ts
  src/pages/people/outlets/texts/index.tsx
  src/pages/people/outlets/texts/interface.tsx
  src/pages/people/outlets/texts/styles.ts
Labels: minor

#529 Create Menu for selecting palette color tokens
  .storybook/preview-body.html
  src/components/cards/FieldsetColorCard/FieldsetColorCard.stories.tsx
  src/components/cards/FieldsetColorCard/index.tsx
  src/components/cards/FieldsetColorCard/styles.ts
  src/components/cards/FieldsetColorCard/types.ts
  src/components/cards/TokenColorCard/TokenColorCard.stories.tsx
  src/components/cards/TokenColorCard/index.tsx
  src/components/cards/TokenColorCard/styles.ts
  src/components/feedback/Popup/Popup.stories.tsx
  src/components/feedback/Popup/index.tsx
  src/components/feedback/Popup/styles.ts
  src/components/feedback/Popup/types.ts
  src/components/forms/submit/FormButtons/index.tsx
  src/pages/people/outlets/palette/index.tsx
  src/pages/people/outlets/palette/interface.tsx
  src/pages/people/outlets/texts/form/DarkForm/index.tsx
  src/pages/people/outlets/texts/form/DarkForm/interface.tsx
  src/pages/people/outlets/texts/form/ErrorForm/index.tsx
  src/pages/people/outlets/texts/form/ErrorForm/interface.tsx
  src/pages/people/outlets/texts/form/GrayForm/index.tsx
  src/pages/people/outlets/texts/form/GrayForm/interface.tsx
  src/pages/people/outlets/texts/form/HelpForm/index.tsx
  src/pages/people/outlets/texts/form/HelpForm/interface.tsx
  src/pages/people/outlets/texts/form/InformationForm/index.tsx
  src/pages/people/outlets/texts/form/InformationForm/interface.tsx
  src/pages/people/outlets/texts/form/LightForm/index.tsx
  src/pages/people/outlets/texts/form/LightForm/interface.tsx
  src/pages/people/outlets/texts/form/PrimaryForm/index.tsx
  src/pages/people/outlets/texts/form/PrimaryForm/interface.tsx
  src/pages/people/outlets/texts/form/SuccessForm/index.tsx
  src/pages/people/outlets/texts/form/SuccessForm/interface.tsx
  src/pages/people/outlets/texts/form/WarningForm/index.tsx
  src/pages/people/outlets/texts/form/WarningForm/interface.tsx
  src/pages/people/outlets/texts/index.tsx
  src/pages/people/outlets/texts/interface.tsx
Labels: minor

#530 Create Menu for selecting palette color tokens
  src/components/cards/FieldsetColorCard/FieldsetColorCard.stories.tsx
  src/components/cards/FieldsetColorCard/index.tsx
  src/components/cards/FieldsetColorCard/styles.ts
  src/components/cards/FieldsetColorCard/types.ts
  src/components/inputs/Fieldset/index.tsx
  src/pages/people/outlets/texts/form/DarkForm/interface.tsx
  src/pages/people/outlets/texts/form/ErrorForm/interface.tsx
  src/pages/people/outlets/texts/form/GrayForm/interface.tsx
  src/pages/people/outlets/texts/form/HelpForm/interface.tsx
  src/pages/people/outlets/texts/form/InformationForm/interface.tsx
  src/pages/people/outlets/texts/form/LightForm/interface.tsx
  src/pages/people/outlets/texts/form/PrimaryForm/interface.tsx
  src/pages/people/outlets/texts/form/SuccessForm/interface.tsx
  src/pages/people/outlets/texts/form/WarningForm/interface.tsx
Labels: minor

#531 `Feat:` Implementation of Mock Screen for `Text Color` Token Editing
  src/components/cards/FieldsetColorCard/index.tsx
  src/components/cards/FieldsetColorCard/styles.ts
  src/pages/people/outlets/texts/config/text.config.tsx
  src/pages/people/outlets/texts/form/DarkForm/index.tsx
  src/pages/people/outlets/texts/form/DarkForm/interface.tsx
  src/pages/people/outlets/texts/form/ErrorForm/index.tsx
  src/pages/people/outlets/texts/form/ErrorForm/interface.tsx
  src/pages/people/outlets/texts/form/GrayForm/index.tsx
  src/pages/people/outlets/texts/form/GrayForm/interface.tsx
  src/pages/people/outlets/texts/form/HelpForm/index.tsx
  src/pages/people/outlets/texts/form/HelpForm/interface.tsx
  src/pages/people/outlets/texts/form/InformationForm/index.tsx
  src/pages/people/outlets/texts/form/InformationForm/interface.tsx
  src/pages/people/outlets/texts/form/LightForm/index.tsx
  src/pages/people/outlets/texts/form/LightForm/interface.tsx
  src/pages/people/outlets/texts/form/PrimaryForm/index.tsx
  src/pages/people/outlets/texts/form/PrimaryForm/interface.tsx
  src/pages/people/outlets/texts/form/SuccessForm/index.tsx
  src/pages/people/outlets/texts/form/SuccessForm/interface.tsx
  src/pages/people/outlets/texts/form/WarningForm/index.tsx
  src/pages/people/outlets/texts/form/WarningForm/interface.tsx
  src/pages/people/outlets/texts/index.tsx
  src/pages/people/outlets/texts/interface.tsx
Labels: minor

#532 Extension of Pre-Commit Hook to Include ESLint Execution
  .husky/pre-commit
  package.json
  src/components/cards/FieldsetColorCard/index.tsx
  src/components/cards/SearchUserCard/SubjectCard.stories.tsx
  src/components/cards/SearchUserCard/styles.ts
  src/components/cards/SubjectSearchCard/SubjectSearchCard.stories.tsx
  src/components/cards/TokenColorCard/TokenColorCard.stories.tsx
  src/components/feedback/DecisionModal/index.tsx
  src/components/feedback/Popup/Popup.stories.tsx
  src/components/layout/AppPage/styles.ts
  src/components/navigation/Menu/index.tsx
  src/components/navigation/MenuOption/styles.ts
  src/mocks/apps/privileges/users/usersSearchField.mock.tsx
  src/pages/login/outlets/CheckingCredentials/index.tsx
  src/pages/login/outlets/LoadingApp/index.tsx
  src/pages/people/outlets/lines/interface.tsx
  src/pages/people/outlets/options/config/people.config.tsx
  src/pages/people/outlets/texts/form/ErrorForm/index.tsx
  src/pages/people/outlets/texts/form/ErrorForm/interface.tsx
  src/pages/people/outlets/texts/form/GrayForm/index.tsx
  src/pages/people/outlets/texts/form/GrayForm/interface.tsx
  src/pages/people/outlets/texts/form/LightForm/index.tsx
  src/pages/people/outlets/texts/form/WarningForm/index.tsx
  src/pages/people/outlets/texts/form/WarningForm/interface.tsx
  src/pages/people/outlets/texts/interface.tsx
Labels: bug

#539 Build a customized component to render tab content according to the type of tokens for Text
  src/components/cards/FieldsetColorCard/index.tsx
  src/pages/people/outlets/texts/config/text.config.tsx
  src/pages/people/outlets/texts/form/DarkForm/index.tsx
  src/pages/people/outlets/texts/form/DarkForm/interface.tsx
  src/pages/people/outlets/texts/form/ErrorForm/index.tsx
  src/pages/people/outlets/texts/form/ErrorForm/styles.ts
  src/pages/people/outlets/texts/form/GrayForm/index.tsx
  src/pages/people/outlets/texts/form/GrayForm/interface.tsx
  src/pages/people/outlets/texts/form/GrayForm/styles.ts
  src/pages/people/outlets/texts/form/HelpForm/index.tsx
  src/pages/people/outlets/texts/form/HelpForm/interface.tsx
  src/pages/people/outlets/texts/form/HelpForm/styles.ts
  src/pages/people/outlets/texts/form/InformationForm/index.tsx
  src/pages/people/outlets/texts/form/InformationForm/interface.tsx
  src/pages/people/outlets/texts/form/InformationForm/styles.ts
  src/pages/people/outlets/texts/form/LightForm/index.tsx
  src/pages/people/outlets/texts/form/LightForm/interface.tsx
  src/pages/people/outlets/texts/form/LightForm/styles.ts
  src/pages/people/outlets/texts/form/PrimaryForm/index.tsx
  src/pages/people/outlets/texts/form/PrimaryForm/interface.tsx
  src/pages/people/outlets/texts/form/PrimaryForm/styles.ts
  src/pages/people/outlets/texts/form/RenderTextContentForm/index.tsx
  src/pages/people/outlets/texts/form/RenderTextContentForm/interface.tsx
  src/pages/people/outlets/texts/form/RenderTextContentForm/styles.ts
  src/pages/people/outlets/texts/form/SuccessForm/index.tsx
  src/pages/people/outlets/texts/form/SuccessForm/interface.tsx
  src/pages/people/outlets/texts/form/SuccessForm/styles.ts
  src/pages/people/outlets/texts/form/WarningForm/index.tsx
  src/pages/people/outlets/texts/form/WarningForm/interface.tsx
  src/pages/people/outlets/texts/form/WarningForm/styles.ts
  src/pages/people/outlets/texts/index.tsx
  src/pages/people/outlets/texts/interface.tsx
  src/routes/people.tsx
Labels: minor

#541 Personas: Adjust `<Text/>` to resolve issues with the element reference
  src/components/cards/FieldsetColorCard/index.tsx
  src/components/cards/FieldsetColorCard/styles.ts
  src/components/cards/TokenColorCard/styles.ts
  src/pages/people/outlets/texts/form/RenderTextContentForm/index.tsx
Labels: bug

#538 Logout navlink redirects to error page and doesn't log out user
  src/App.tsx
Labels: bug

#540 fix: fixing storybook for palette
  src/pages/people/outlets/palette/Palette.stories.tsx
Labels: bug

#542 add example and controls in surface primary tabs
  src/components/cards/FieldsetColorCard/index.tsx
  src/components/cards/TokenColorCard/index.tsx
  src/components/forms/submit/FormButtons/index.tsx
  src/pages/people/outlets/surfaces/Surfaces.stories.tsx
  src/pages/people/outlets/surfaces/config/surface.config.tsx
  src/pages/people/outlets/surfaces/config/surfaceTabs.config.ts
  src/pages/people/outlets/surfaces/form/RenderContentFormSurface/RenderSurfaceContentForm.stories.tsx
  src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
  src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
  src/pages/people/outlets/surfaces/form/RenderContentFormSurface/styles.ts
  src/pages/people/outlets/surfaces/index.tsx
  src/pages/people/outlets/surfaces/interface.tsx
  src/routes/people.tsx
Labels: minor

#555 Personas: mock the screen to check and edit the stroke color tokens
  src/components/cards/FieldsetColorCard/index.tsx
  src/components/forms/submit/FormButtons/index.tsx
  src/pages/people/outlets/lines/Lines.stories.tsx
  src/pages/people/outlets/lines/config/lines.config.tsx
  src/pages/people/outlets/lines/config/linesTabs.config.ts
  src/pages/people/outlets/lines/form/RenderLinesContentForm/RenderLinesContentForm.stories.tsx
  src/pages/people/outlets/lines/form/RenderLinesContentForm/index.tsx
  src/pages/people/outlets/lines/form/RenderLinesContentForm/interface.tsx
  src/pages/people/outlets/lines/form/RenderLinesContentForm/styles.ts
  src/pages/people/outlets/lines/form/RenderLinesWithLinkForm/RenderLinesWithLinkForm.stories.tsx
  src/pages/people/outlets/lines/form/RenderLinesWithLinkForm/index.tsx
  src/pages/people/outlets/lines/form/RenderLinesWithLinkForm/interface.tsx
  src/pages/people/outlets/lines/form/RenderLinesWithLinkForm/styles.ts
  src/pages/people/outlets/lines/form/RenderLinesWithSpinnerForm/RenderLinesWithSpinnerForm.stories.tsx
  src/pages/people/outlets/lines/form/RenderLinesWithSpinnerForm/index.tsx
  src/pages/people/outlets/lines/form/RenderLinesWithSpinnerForm/interface.tsx
  src/pages/people/outlets/lines/form/RenderLinesWithSpinnerForm/styles.ts
  src/pages/people/outlets/lines/index.tsx
  src/pages/people/outlets/lines/interface.tsx
  src/pages/people/outlets/lines/styles.ts
  src/pages/people/outlets/texts/Texts.stories.tsx
  src/pages/people/outlets/texts/form/RenderTextContentForm/interface.tsx
  src/pages/people/outlets/types/people.types.ts
  src/routes/people.tsx
Labels: minor

#549 Adjust responsive of options screen
  src/components/cards/AppMenuCard/styles.ts
  src/components/layout/AppMenu/index.tsx
Labels: bug

#550 Change Success appearance buttons for Primary buttons in Privileges screens
  src/components/feedback/DecisionModal/index.tsx
  src/pages/privileges/outlets/users/invite/interface.tsx
Labels: bug

#557 Fix: Adjust <Surface/> in order to avoid use any type
  src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
  src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
  src/pages/people/outlets/surfaces/interface.tsx
Labels: minor

#556 Fix: Adjust <Text/> component to ensure proper functionality.
  src/pages/people/outlets/texts/Texts.stories.tsx
  src/pages/people/outlets/texts/config/textsTabs.config.ts
  src/pages/people/outlets/texts/form/RenderTextContentForm/RenderTextContentForm.stories.tsx
  src/pages/people/outlets/texts/form/RenderTextContentForm/index.tsx
  src/pages/people/outlets/texts/form/RenderTextContentForm/interface.tsx
  src/pages/people/outlets/texts/index.tsx
  src/pages/people/outlets/texts/interface.tsx
Labels: minor

#558 Upgrade to the latest version of the design system to access its newest features and fixes
  package-lock.json
  package.json
Labels: dependencies

#547 Fix: Optimizing the <SendingInformation/> Component for Tablet Responsiveness
  src/components/feedback/SendingInformation/SendingInformation.stories.tsx
  src/components/feedback/SendingInformation/config/sectionMessage.initState.tsx
  src/components/feedback/SendingInformation/config/sectionMessage.state.ts
  src/components/feedback/SendingInformation/index.tsx
  src/components/feedback/SendingInformation/props.ts
  src/components/feedback/SendingInformation/styles.ts
  src/components/feedback/SendingInformation/types.ts
Labels: bug

#553 Fix: Correcting the Misaligned Palette Display Relative to the 'tokenName' Picker
  src/components/cards/FieldsetColorCard/FieldsetColorCard.stories.tsx
  src/components/cards/FieldsetColorCard/index.tsx
  src/components/cards/FieldsetColorCard/styles.ts
  src/components/cards/TokenColorCard/TokenColorCard.stories.tsx
  src/components/cards/TokenColorCard/index.tsx
  src/components/cards/TokenColorCard/styles.ts
  src/components/feedback/Popup/index.tsx
  src/components/feedback/Popup/styles.ts
  src/components/feedback/Popup/types.ts
  src/pages/people/outlets/lines/form/RenderLinesContentForm/index.tsx
  src/pages/people/outlets/lines/form/RenderLinesContentForm/interface.tsx
  src/pages/people/outlets/lines/form/RenderLinesWithLinkForm/index.tsx
  src/pages/people/outlets/lines/form/RenderLinesWithLinkForm/interface.tsx
  src/pages/people/outlets/lines/form/RenderLinesWithSpinnerForm/index.tsx
  src/pages/people/outlets/lines/form/RenderLinesWithSpinnerForm/interface.tsx
  src/pages/people/outlets/lines/interface.tsx
  src/pages/people/outlets/palette/interface.tsx
  src/pages/people/outlets/texts/form/RenderTextContentForm/index.tsx
  src/pages/people/outlets/texts/form/RenderTextContentForm/interface.tsx
Labels: bug

#560 Adjust spacing between buttons and inputs
  src/components/forms/submit/FormButtons/index.tsx
Labels: bug

#559 Mock surface token tab for <NavLink />
  src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
  src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
  src/pages/people/outlets/surfaces/form/RenderContentFormSurface/styles.ts
Labels: minor
