Repository selsa-inube/isetting, pull requests merged in 2024-02, with the labels that each got.

#571 Create /AppContext directory in context/ to store there current files
  src/App.tsx
  src/components/layout/AppPage/index.tsx
  src/context/AppContext/index.tsx
  src/context/AppContext/types.ts
  src/pages/home/Home.stories.tsx
  src/pages/home/interface.tsx
Labels: minor

#574 Use @pages instead of @src when importing pages in routes/people.tsx
  src/routes/people.tsx
Labels: minor

#575 Update <Palette/> according to the figma design
  src/components/cards/TokenColorCard/index.tsx
  src/components/cards/TokenColorCard/styles.ts
  src/pages/people/outlets/palette/config/palette.config.tsx
  src/pages/people/outlets/palette/config/paletteTabs.config.ts
  src/pages/people/outlets/palette/form/RenderContentFormNeutralPalette/RenderContentFormNeutralPalette.stories.tsx
  src/pages/people/outlets/palette/form/RenderContentFormNeutralPalette/index.tsx
  src/pages/people/outlets/palette/form/RenderContentFormNeutralPalette/interface.tsx
  src/pages/people/outlets/palette/form/RenderContentFormNeutralPalette/styles.ts
  src/pages/people/outlets/palette/form/RenderContentFormPalette/RenderContentFormPalette.stories.tsx
  src/pages/people/outlets/palette/form/RenderContentFormPalette/index.tsx
  src/pages/people/outlets/palette/form/RenderContentFormPalette/interface.tsx
  src/pages/people/outlets/palette/form/RenderContentFormPalette/styles.ts
  src/pages/people/outlets/palette/index.tsx
  src/pages/people/outlets/palette/interface.tsx
  src/pages/people/outlets/palette/styles.ts
Labels: minor

#588 Update the package.json file to ensure it retrieves the most recent version of the design-system package
  package-lock.json
  package.json
Labels: dependencies

#590 update env file in order to change the redirect_uri path
  .env
Labels: bug

#564 Last crumb in <Breadcrumbs /> should use a dark neutral color
  src/pages/home/config/apps.config.tsx
Labels: bug

#586 Change all references to "lines" to "strokes" to align pages and components to token name
  src/pages/people/outlets/options/config/people.config.tsx
  src/pages/people/outlets/strokes/Strokes.stories.tsx
  src/pages/people/outlets/strokes/config/Strokes.config.tsx
  src/pages/people/outlets/strokes/config/strokesTabs.config.ts
  src/pages/people/outlets/strokes/form/RenderStrokesContentForm/RenderStrokesContentForm.stories.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesContentForm/index.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesContentForm/interface.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesContentForm/styles.ts
  src/pages/people/outlets/strokes/form/RenderStrokesWithLinkForm/RenderStrokesWithLinkForm.stories.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithLinkForm/index.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithLinkForm/interface.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithLinkForm/styles.ts
  src/pages/people/outlets/strokes/form/RenderStrokesWithSpinnerForm/RenderStrokesWithSpinnerForm.stories.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithSpinnerForm/index.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithSpinnerForm/interface.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithSpinnerForm/styles.ts
  src/pages/people/outlets/strokes/index.tsx
  src/pages/people/outlets/strokes/interface.tsx
  src/pages/people/outlets/strokes/styles.ts
  src/routes/people.tsx
Labels: minor

#573 Mock the process of requesting a backend service for representable clients
  .env
  src/App.tsx
  src/assets/clients-mocks/cooservunal.png
  src/assets/clients-mocks/corbanca.png
  src/assets/clients-mocks/fondecom.png
  src/context/AppContext/index.tsx
  src/context/AppContext/types.ts
  src/mocks/login/clients.mock.tsx
  src/pages/login/index.tsx
  src/pages/login/outlets/CheckingCredentials/index.tsx
  src/pages/login/outlets/Clients/index.tsx
  src/pages/login/outlets/Clients/interface.tsx
  src/pages/login/outlets/Clients/types.ts
  src/routes/login.tsx
Labels: enhancement

#572 Create a `<TokenContext/>` for storing token state with its setter and handleSubmit
  src/context/TokenContext/index.tsx
  src/context/TokenContext/types.ts
  src/mocks/themeService/themeService.mock.ts
  src/pages/people/outlets/palette/Palette.stories.tsx
  src/pages/people/outlets/palette/form/RenderContentFormNeutralPalette/index.tsx
  src/pages/people/outlets/palette/form/RenderContentFormPalette/index.tsx
  src/pages/people/outlets/palette/index.tsx
  src/pages/people/outlets/palette/interface.tsx
  src/pages/people/outlets/strokes/Strokes.stories.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesContentForm/index.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesContentForm/interface.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithLinkForm/index.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithLinkForm/interface.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithSpinnerForm/index.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithSpinnerForm/interface.tsx
  src/pages/people/outlets/strokes/index.tsx
  src/pages/people/outlets/strokes/interface.tsx
  src/pages/people/outlets/surfaces/Surfaces.stories.tsx
  src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
  src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
  src/pages/people/outlets/surfaces/form/RenderContentFormSurfaceBlanket/index.tsx
  src/pages/people/outlets/surfaces/index.tsx
  src/pages/people/outlets/surfaces/interface.tsx
  src/pages/people/outlets/texts/Texts.stories.tsx
  src/pages/people/outlets/texts/form/RenderTextContentForm/index.tsx
  src/pages/people/outlets/texts/form/RenderTextContentForm/interface.tsx
  src/pages/people/outlets/texts/index.tsx
  src/pages/people/outlets/texts/interface.tsx
  src/routes/people.tsx
  tsconfig.json
Labels: minor

#593 Fix: Adjust <ClientsUI/> so please make sure that clients images appear
  public/cooservunal.png
  public/corbanca.png
  public/fondecom.png
  src/mocks/login/clients.mock.tsx
Labels: minor

#587 Adjust the `<TokenColorCard/>` Component for Independence and Dependency Optimization
  src/components/cards/TokenColorCard/index.tsx
  src/components/layout/RenderCategoryGrid/index.tsx
  src/components/layout/RenderCategoryGrid/stories/RenderCategoryGrid.Controller.tsx
  src/components/layout/RenderCategoryGrid/stories/RenderCategoryGrid.stories.tsx
  src/components/layout/RenderCategoryGrid/stories/props.ts
  src/components/layout/RenderCategoryGrid/styles.ts
  src/pages/people/outlets/palette/form/RenderContentFormNeutralPalette/RenderContentFormNeutralPalette.stories.tsx
  src/pages/people/outlets/palette/form/RenderContentFormNeutralPalette/index.tsx
  src/pages/people/outlets/palette/form/RenderContentFormNeutralPalette/interface.tsx
  src/pages/people/outlets/palette/form/RenderContentFormNeutralPalette/styles.ts
  src/pages/people/outlets/palette/form/RenderContentFormPalette/interface.tsx
  src/pages/people/outlets/palette/interface.tsx
Labels: enhancement

#598 Adjust the <Strokes/> configuration to display two columns instead of three, as specified in the Figma design
  src/pages/people/outlets/strokes/form/RenderStrokesContentForm/interface.tsx
Labels: minor

#597 Adjust the <Surfaces/> configuration to display two columns instead of three, as specified in the Figma design
  src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
Labels: minor

#602 Adjust the authentication management to correct the issue of being redirected incorrectly due to token storage
  src/components/layout/AppPage/index.tsx
Labels: bug

#600 Including tokens from different clients
  src/mocks/design/themes/cooservunal/color/color.ts
  src/mocks/design/themes/cooservunal/color/palette.ts
  src/mocks/design/themes/cooservunal/color/stroke.ts
  src/mocks/design/themes/cooservunal/color/surface.ts
  src/mocks/design/themes/cooservunal/color/text.ts
  src/mocks/design/themes/cooservunal/index.ts
  src/mocks/design/themes/cooservunal/typography/body.ts
  src/mocks/design/themes/cooservunal/typography/display.ts
  src/mocks/design/themes/cooservunal/typography/fonts.ts
  src/mocks/design/themes/cooservunal/typography/headline.ts
  src/mocks/design/themes/cooservunal/typography/label.ts
  src/mocks/design/themes/cooservunal/typography/title.ts
  src/mocks/design/themes/cooservunal/typography/typography.ts
  src/mocks/design/themes/corbanca/color/color.ts
  src/mocks/design/themes/corbanca/color/palette.ts
  src/mocks/design/themes/corbanca/color/stroke.ts
  src/mocks/design/themes/corbanca/color/surface.ts
  src/mocks/design/themes/corbanca/color/text.ts
  src/mocks/design/themes/corbanca/index.ts
  src/mocks/design/themes/corbanca/typography/body.ts
  src/mocks/design/themes/corbanca/typography/display.ts
  src/mocks/design/themes/corbanca/typography/fonts.ts
  src/mocks/design/themes/corbanca/typography/headline.ts
  src/mocks/design/themes/corbanca/typography/label.ts
  src/mocks/design/themes/corbanca/typography/title.ts
  src/mocks/design/themes/corbanca/typography/typography.ts
  src/mocks/design/themes/fondecom/color/color.ts
  src/mocks/design/themes/fondecom/color/palette.ts
  src/mocks/design/themes/fondecom/color/stroke.ts
  src/mocks/design/themes/fondecom/color/surface.ts
  src/mocks/design/themes/fondecom/color/text.ts
  src/mocks/design/themes/fondecom/index.ts
  src/mocks/design/themes/fondecom/typography/body.ts
  src/mocks/design/themes/fondecom/typography/display.ts
  src/mocks/design/themes/fondecom/typography/fonts.ts
  src/mocks/design/themes/fondecom/typography/headline.ts
  src/mocks/design/themes/fondecom/typography/label.ts
  src/mocks/design/themes/fondecom/typography/title.ts
  src/mocks/design/themes/fondecom/typography/typography.ts
  src/mocks/design/themes/index.ts
Labels: minor

#606 Refactor the `renderMessage` function/component
  src/components/feedback/RenderMessage/RenderMessage.stories.tsx
  src/components/feedback/RenderMessage/index.tsx
  src/components/feedback/RenderMessage/styles.ts
  src/mocks/themeService/themeService.mock.ts
  src/pages/people/outlets/palette/form/RenderContentFormPalette/index.tsx
  src/pages/people/outlets/palette/form/RenderContentFormPalette/interface.tsx
  src/pages/people/outlets/palette/form/RenderContentFormPalette/styles.ts
  src/pages/people/outlets/strokes/form/RenderStrokesContentForm/index.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesContentForm/interface.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithLinkForm/index.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithLinkForm/interface.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithLinkForm/styles.ts
  src/pages/people/outlets/strokes/form/RenderStrokesWithSpinnerForm/index.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithSpinnerForm/interface.tsx
  src/pages/people/outlets/strokes/form/RenderStrokesWithSpinnerForm/styles.ts
  src/pages/people/outlets/strokes/styles.ts
  src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
  src/pages/people/outlets/surfaces/form/RenderContentFormSurface/styles.ts
  src/pages/people/outlets/surfaces/form/RenderContentFormSurfaceBlanket/interface.tsx
  src/pages/people/outlets/surfaces/form/RenderContentFormSurfaceBlanket/styles.ts
  src/pages/people/outlets/surfaces/styles.ts
  src/pages/people/outlets/texts/form/RenderTextContentForm/interface.tsx
  src/pages/people/outlets/texts/form/RenderTextContentForm/styles.ts
  src/pages/people/outlets/texts/styles.ts
  src/pages/people/outlets/typography/fonts/form/RenderFormFonts/RenderFormFonts.stories.tsx
  src/pages/people/outlets/typography/fonts/form/RenderFormFonts/interface.tsx
  src/pages/people/outlets/typography/fonts/form/RenderFormFonts/styles.ts
  src/pages/people/outlets/typography/fonts/styles.ts
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/AidBudgetsForm/styles.ts
  src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/BranchesForm/styles.ts
  src/pages/privileges/outlets/users/edit-user/forms/EventsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/EventsForm/styles.ts
  src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/PayrollsForm/styles.ts
  src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/interface.tsx
  src/pages/privileges/outlets/users/edit-user/forms/ProjectsForm/styles.ts
  src/pages/privileges/outlets/users/interface.tsx
Labels: performance

#604 Create a Color folder into people/outlets grouping the color blocks
  src/components/layout/RenderCategoryGrid/index.tsx
  src/pages/people/outlets/color/palette/Palette.stories.tsx
  src/pages/people/outlets/color/palette/config/palette.config.tsx
  src/pages/people/outlets/color/palette/config/paletteTabs.config.ts
  src/pages/people/outlets/color/palette/form/RenderContentFormPalette/RenderContentFormPalette.stories.tsx
  src/pages/people/outlets/color/palette/form/RenderContentFormPalette/index.tsx
  src/pages/people/outlets/color/palette/form/RenderContentFormPalette/interface.tsx
  src/pages/people/outlets/color/palette/index.tsx
  src/pages/people/outlets/color/palette/interface.tsx
  src/pages/people/outlets/color/palette/styles.ts
  src/pages/people/outlets/color/strokes/Strokes.stories.tsx
  src/pages/people/outlets/color/strokes/config/Strokes.config.tsx
  src/pages/people/outlets/color/strokes/config/strokesTabs.config.ts
  src/pages/people/outlets/color/strokes/form/RenderStrokesContentForm/RenderStrokesContentForm.stories.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesContentForm/index.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesContentForm/interface.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesWithLinkForm/RenderStrokesWithLinkForm.stories.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesWithLinkForm/index.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesWithLinkForm/interface.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesWithLinkForm/styles.ts
  src/pages/people/outlets/color/strokes/form/RenderStrokesWithSpinnerForm/RenderStrokesWithSpinnerForm.stories.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesWithSpinnerForm/index.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesWithSpinnerForm/interface.tsx
  src/pages/people/outlets/color/strokes/index.tsx
  src/pages/people/outlets/color/strokes/interface.tsx
  src/pages/people/outlets/color/strokes/styles.ts
  src/pages/people/outlets/color/surfaces/Surfaces.stories.tsx
  src/pages/people/outlets/color/surfaces/config/surface.config.tsx
  src/pages/people/outlets/color/surfaces/config/surfaceTabs.config.ts
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/RenderSurfaceContentForm.stories.tsx
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/index.tsx
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/interface.tsx
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/styles.ts
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurfaceBlanket/RenderContentFormSurfaceBlanket.stories.tsx
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurfaceBlanket/index.tsx
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurfaceBlanket/interface.tsx
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurfaceBlanket/styles.ts
  src/pages/people/outlets/color/surfaces/index.tsx
  src/pages/people/outlets/color/surfaces/interface.tsx
  src/pages/people/outlets/color/surfaces/styles.ts
  src/pages/people/outlets/color/texts/Texts.stories.tsx
  src/pages/people/outlets/color/texts/config/text.config.tsx
  src/pages/people/outlets/color/texts/config/textsTabs.config.ts
  src/pages/people/outlets/color/texts/form/RenderTextContentForm/RenderTextContentForm.stories.tsx
  src/pages/people/outlets/color/texts/form/RenderTextContentForm/index.tsx
  src/pages/people/outlets/color/texts/form/RenderTextContentForm/interface.tsx
  src/pages/people/outlets/color/texts/index.tsx
  src/pages/people/outlets/color/texts/interface.tsx
  src/pages/people/outlets/color/texts/styles.ts
  src/routes/people.tsx
Labels: minor

#608 The storybook is not working in Clients or in loading-app
  src/pages/login/outlets/CheckingCredentials/CheckingCredentials.stories.tsx
  src/pages/login/outlets/CheckingCredentials/index.tsx
  src/pages/login/outlets/Clients/Clients.stories.tsx
  src/pages/login/outlets/LoadingApp/LoadingApp.stories.tsx
Labels: bug

#607 Add modal to confirm logout action
  src/components/feedback/LogoutModal/LogoutModal.stories.tsx
  src/components/feedback/LogoutModal/index.tsx
  src/components/feedback/LogoutModal/styles.ts
  src/components/feedback/RenderMessage/RenderMessage.stories.tsx
Labels: enhancement

#610 The client token mock-up is experiencing loading issues
  src/context/TokenContext/index.tsx
  src/context/TokenContext/types.ts
  src/mocks/themeService/themeService.mock.ts
  src/pages/people/outlets/color/palette/form/RenderContentFormPalette/index.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesContentForm/index.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesWithLinkForm/index.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesWithSpinnerForm/index.tsx
  src/pages/people/outlets/color/surfaces/form/RenderContentFormNav/index.tsx
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/index.tsx
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurfaceBlanket/index.tsx
  src/pages/people/outlets/color/texts/form/RenderTextContentForm/index.tsx
  src/pages/people/outlets/typography/fonts/form/RenderFormFonts/index.tsx
Labels: bug

#613 Misplaced Appearance type
  src/pages/people/outlets/color/palette/form/RenderContentFormPalette/index.tsx
  src/pages/people/outlets/color/palette/form/RenderContentFormPalette/interface.tsx
  src/pages/people/outlets/color/palette/interface.tsx
  src/pages/people/outlets/color/palette/types.ts
  src/pages/people/outlets/color/strokes/form/RenderStrokesContentForm/index.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesContentForm/interface.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesWithLinkForm/index.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesWithLinkForm/interface.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesWithLinkForm/styles.ts
  src/pages/people/outlets/color/strokes/form/RenderStrokesWithSpinnerForm/index.tsx
  src/pages/people/outlets/color/strokes/form/RenderStrokesWithSpinnerForm/interface.tsx
  src/pages/people/outlets/color/strokes/interface.tsx
  src/pages/people/outlets/color/strokes/types.ts
  src/pages/people/outlets/color/surfaces/form/RenderContentFormNav/index.tsx
  src/pages/people/outlets/color/surfaces/form/RenderContentFormNav/interface.tsx
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/index.tsx
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/interface.tsx
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurfaceBlanket/index.tsx
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurfaceBlanket/interface.tsx
  src/pages/people/outlets/color/surfaces/interface.tsx
  src/pages/people/outlets/color/texts/form/RenderTextContentForm/index.tsx
  src/pages/people/outlets/color/texts/form/RenderTextContentForm/interface.tsx
  src/pages/people/outlets/color/texts/interface.tsx
  src/pages/people/outlets/color/texts/types.ts
Labels: bug

#617 Fix for `RenderSurfaceContentForm` Token Rendering Issues
  src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/index.tsx
Labels: bug

#624 Fix: Incorrect Text Color Issue in tokenColorCard Component
  src/components/cards/TokenColorCard/index.tsx
Labels: bug

#623 Adjust the clients page acoording to the wireframes
  src/components/cards/RadioClient/index.tsx
  src/components/cards/RadioClient/styles.ts
  src/mocks/login/clients.mock.tsx
  src/pages/login/outlets/Clients/styles.ts
Labels: bug

#618 Fix: Adjust the isetting as there are times when it works and times when it does not
  src/App.tsx
  src/context/AppContext/index.tsx
  src/context/AppContext/types.ts
  src/pages/login/outlets/Clients/index.tsx
Labels: bug
